### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'email.html'

### ISSUE THREAD

**Issue by Swjtu-only** [woodfrog/floor-sp#3]
when i run "python download_from_eamil.py",Display an error that No such file or directory: 'email.html'。
can u  provide an email link?

**Comment by woodfrog** [comment]
Hi, 

Please read the README carefully: "To prepare the data, first fill the form on Beike's website to get the email containing the download links. Download the email from Beike and save the HTML file into ./data/email.html. Then run ./data/download.sh to download all the 100 data and unzip them automatically". The link to Beike's website is also available in the README.  I cannot provide the download links directly since everyone who requires the data is supposed to get it from Beike.

Thanks!

**Comment by Swjtu-only** [comment]
> Please read the README carefully: "To prepare the data, first fill the form on Beike's website to get the email containing the download links. Download the email from Beike and save the HTML file into ./data/email.html. Then run ./data/download.sh to download all the 100 data and unzip them automatically". The link to Beike's website is also available in the README. I cannot provide the download links directly since everyone who requires the data is supposed to get it from Beike.

Nice reply and project,I have run your code completely once.
